name: Jest Coverage Comment

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - test-dynamic-multiple-files

jobs:
  jest-coverage-comment:
    name: Jest Coverage Comment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: NPM Cache
      #   id: npm-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-npm

      # - name: Install Dependencies
      #   if: steps.npm-cache.outputs.cache-hit != 'true'
      #   run: npm ci

      # - name: Run Tests
      #   run: npm run coverage | tee ./coverage.txt

      - name: Read dynamic-multiple-files.txt
        id: multiple
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: ./data/dynamic-multiple-files.txt

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          multiple-files: ${{ steps.multiple.outputs.content }}
