name: Jest Coverage Comment

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - test-multiple-files

jobs:
  jest-coverage-comment:
    name: Jest Coverage Comment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: NPM Cache
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        run: npm run coverage | tee ./coverage.txt

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          title: My Jest Coverage Comment
          multiple-files: |
            ui, ./coverage/coverage-summary.json
            backend, ./coverage/coverage-summary.json
          # summary-title: My Summary Title
          # badge-title: Coverage
          # hide-comment: false
          # create-new-comment: false
          # hide-summary: false
          # report-only-changed-files: true
          # junitxml-title: My Junit Title
          # junitxml-path: ./coverage/junit.xml
          # coverage-title: My Coverage Title
          # coverage-path: ./coverage.txt
