name: Jest Coverage

on:
  pull_request:

jobs:
  jest-coverage:
    name: Jest Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependdencies
        run: npm ci

      - name: Run tests
        run: npm run coverage

      - uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
