name: Jest Coverage Comment

on:
  pull_request:
  push:
    branches:
      - test-multiple-junit-files

jobs:
  jest-coverage-comment:
    name: Jest Coverage Comment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: NPM Cache
      #   id: npm-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-npm

      # - name: Install Dependencies
      #   if: steps.npm-cache.outputs.cache-hit != 'true'
      #   run: npm ci

      # - name: Run Tests
      #   run: npm run coverage | tee ./coverage.txt

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@support-multiple-junitxml-files
        with:
          # title: My Jest Coverage Comment
          # summary-title: My Summary Title
          # badge-title: Coverage
          # hide-comment: false
          # create-new-comment: false
          # hide-summary: false
          # report-only-changed-files: false
          # junitxml-title: My Junit Title
          # junitxml-path: ./data/junit.xml
          # coverage-title: My Coverage Title
          # coverage-path: ./coverage.txt
          multiple-junitxml-files: |
            My-Title-1, ./data/junit.xml
            My-Title-2, ./data/junit.xml
