name: Update Coverage on Readme
on:
  push:
    branches:
      - test-xml-pytest-coverage
jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./data/coverage_1.xml
          # hide-comment: true
          # pytest-coverage-path: ./data/pytest-coverage_1.txt
          # junitxml-path: ./data/pytest_1.xml

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"

      # - name: Create Variable of Summary Report
      #   id: summary_report
      #   run: |
      #     SUMMARY_REPORT=${{ steps.coverageComment.outputs.summaryReport }}
      #     echo "::set-output name=content::$SUMMARY_REPORT"

      # - name: Update Readme with Coverage Html
      #   run: |
      #     sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.summary_report.outputs.content }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      # - name: Commit & Push changes to Readme
      #   uses: actions-js/push@master
      #   with:
      #     message: Update coverage on Readme
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
