name: Update Coverage on Readme
on:
  pull_request:
  # push:
  #   branches:
  #     - test-pytest-matrix-prefix

jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Pytest coverage comment | Python ${{ matrix.python-version }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: false
          pytest-coverage-path: ./data/pytest-coverage_1.txt
          junitxml-path: ./data/pytest_1.xml
          unique-id-for-comment: ${{ matrix.python-version }}
